version: "3.7"
services:
  mysql:
    image: mysql:5.7.30
    container_name: banco
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ramonrrp
      MYSQL_DATABASE: programadorabordo
      MYSQL_USER: ramonrrp
    volumes:
      - "./db/dump:/docker-entrypoint-initdb.d"
      - "./db/data:/var/lib/mysql"
  api:
    image: node
    build: "./api"
    container_name: api
    restart: always
    volumes:
      - "./api:/home/node/app"
    ports:
      - 9001:9001
    depends_on:
      - "mysql"
  php:
    image: php
    build: "./website"
    container_name: front       
    restart: always
    ports:
      - 8888:80
    volumes:
      - "./website:/var/www/html"
    depends_on:
      - "api"
      - "mysql"





